name: rosrobot-proto1 # you probably want to 'snapcraft register <name>'
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: ROS robot prototype1 # 79 char long summary
description: |
  This is ros robot prototype1. It has ros kinetic as a tar ball.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

plugs:
  # Mount the content shared from ros-base into $SNAP/ros-base
  ros-base-armhf:
    content: ros-base-armhf-v1
    interface: content
    target: /ros-base-armhf

apps:

  launch-project:
    command: run-system
    plugs: [network, network-bind, ros-base-armhf]

parts:

  # The `source` here is the tarred staging area of the ros-base snap.
  ros-base-armhf:
    plugin: dump
    source: ros-base-armhf.tar.bz2
    source-type: tar

    # This is only used for building-- filter it out of the final snap.
    prime: [-*]

  rosrobot-proto1:    
    plugin: catkin
    rosdistro: kinetic    
    include-roscore: false
    underlay:
      # Build-time location of the underlay
      # On Pi Platform
      build-path: $SNAPCRAFT_STAGE/opt/ros/kinetic
      
      # On Ubuntu machine
      #build-path: /opt/ros/kinetic

      # Run-time location of the underlay
      run-path: $SNAP/ros-base-armhf/opt/ros/kinetic
    catkin-packages:
      - robot_setup_tf      
    after: [ros-base-armhf]

    stage:
      - -usr/lib/arm-linux-gnueabihf/libasan.so.2.0.0
      - -usr/lib/arm-linux-gnueabihf/libatomic.so.1.1.0
      - -usr/lib/arm-linux-gnueabihf/libgomp.so.1.0.0
      - -usr/lib/arm-linux-gnueabihf/libubsan.so.0.0.0
      - -usr/lib/gcc/arm-linux-gnueabihf/5/crtbegin.o
      - -usr/lib/gcc/arm-linux-gnueabihf/5/crtbeginS.o
      - -usr/lib/gcc/arm-linux-gnueabihf/5/crtbeginT.o
      - -usr/lib/gcc/arm-linux-gnueabihf/5/crtend.o
      - -usr/lib/gcc/arm-linux-gnueabihf/5/crtendS.o
      - -usr/lib/gcc/arm-linux-gnueabihf/5/crtfastmath.o
      - -usr/lib/gcc/arm-linux-gnueabihf/5/libasan.a
      - -usr/lib/gcc/arm-linux-gnueabihf/5/libasan_preinit.o
      - -usr/lib/gcc/arm-linux-gnueabihf/5/libstdc++.a
      - -usr/lib/gcc/arm-linux-gnueabihf/5/libubsan.a
      - -usr/share/doc/linux-libc-dev/changelog.Debian.gz
  
  run-system:
    plugin: dump
    stage: [bin/run-system]
    prime: [bin/run-system]

  mountpoint:
    plugin: nil
    install: mkdir $SNAPCRAFT_PART_INSTALL/ros-base-armhf